export const CLEAR_STATE_CATEGORY = "CLEAR_STATE_CATEGORY";

// REQUEST
export const CATEGORY_REQUEST = "CATEGORY_REQUEST";
export const CATEGORY_REQUEST_SUCCESS = "CATEGORY_REQUEST_SUCCESS";
export const CATEGORY_REQUEST_FAILED = "CATEGORY_REQUEST_FAILED";
