export const CLEAR_STATE_PRODUCT = "CLEAR_STATE_PRODUCT";

// REQUEST
export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_REQUEST_SUCCESS = "PRODUCT_REQUEST_SUCCESS";
export const PRODUCT_REQUEST_FAILED = "PRODUCT_REQUEST_FAILED";
